[package]
name = "q3_test"
version = "0.1.0"
authors = ["raheel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
q3 = {path = "/home/raheel/iot/assig_7/q3"}